version: '3.7'


services:
  redis:
    container_name: redis
    image: redis:4.0.9-alpine
    ports:
      - "6379:6379"
    volumes:
      - "${REDIS_OUTPUT_PATH}:/data/"
    restart: unless-stopped
    entrypoint: redis-server --appendonly yes --requirepass 123456
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    networks:
      - pppoe_system


  mysql:
    container_name: mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'trade'
    ports:
      - "3306:3306"
    #user: mysql
    #privileged: true   # 拥有主机的root权限
    volumes:
      - "${MYSQL_CONFIG_PATH}:/etc/mysql/my.cnf"
      - "${MYSQL_OUTPUT_PATH}:/data/mysql/"
    restart: unless-stopped
    # entrypoint: docker-entrypoint.sh
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --default-time-zone=+08:00
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    networks:
      - pppoe_system


  fluentd:
    container_name: fluentd
    # image: fluent/fluentd:v1.3.2
    build:
       context: ./pppoe_component
       dockerfile: ./dockerfile/fluentd
    ports:
      - "24224:24224"
    volumes:
      - "${FLUENTD_CONFIG_PATH}:/fluentd/etc/fluentd.conf"
      - "${FLUENTD_OUTPUT_PATH}:/data/fluentd/"
    environment:
      FLUENTD_CONF: "fluentd.conf"
      FLUENT_UID: 0
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    networks:
      - pppoe_system


networks:
  pppoe_system:
    name: pppoe_system_network_name
